### PR TITLE
The Great Dogborg Update

### PR DESCRIPTION
**Pull request by Vizoplez**
This is why god left us. Fuck you Mocha. You made me do this

🆑Yawet330
add: Dogborg sprites, modules, code
code: Code now checks for a dogborg flag in modules. May be expanded upon later
/🆑

### CODE REVIEW

**Comment by Vizoplez** [comment]
image
image
image
image

**Comment by Vizoplez** [comment]
Current Modules: Sec, Engineering, Surgeon, Science

**Comment by Knightfall5** [comment]
Kill it with fire

**Comment by Superhats** [comment]
Dogborg issues aside, What exactly makes those different from the already existing modules, beyond bigger sprites?

**Comment by Vizoplez** [comment]
> Dogborg issues aside, What exactly makes those different from the already existing modules, beyond bigger sprites?

...What purpose does any alt-sprite have past being a cosmetic option? Giving people mechanical benefits/disadvantages over a cosmetic change is bad gameplay. It may also be time to reintroduce the research module now that it has more than one sprite lmao

**Comment by bearrrrrrrr** [comment]
absolutely ~~pogtastic~~ dogtastic

**Comment by John-Dang** [comment]
I'm going to try and be as polite as I can be here. I have no idea what got in your head to make this. It is an awful idea. Stop.

**Comment by Vizoplez** [comment]
> I'm going to try and be as polite as I can be here. I have no idea what got in your head to make this. It is an awful idea. Stop.

no
:joker:

**Comment by Alanii** [comment]
NewHestia is not accepting PRs anymore.

If you wish to participate in contributing code to Vesta, please look to the new codebase, Vesta.Bay.

Thanks.

**Comment by Lamasmaster** [comment]
Even if it doesn´t matter now since its old repo, Dogborgs dont belong into our setting and dont exactly add much besides fetish content, codewise this is travesty seeing as they are probably 1 to 1 copy of either skyrats or citadel dogborgs looking at those 250 errors.
Just stop.

**Comment by bearrrrrrrr** [comment]
b ased

**Comment by BurpleBineapple** [comment]
image

**Comment by io-util** [comment]
image

**Comment by io-util** [comment]
Closing this as we are not reviewing / accepting PR's on our old repo anymore.
New Repo: https://github.com/VestaOfOrion/Vesta.Bay/

**Comment by ShaSCT** [comment]
NNNNNNNNNNNNIIIIIIIIIIAAAAAAAAAAAAAAAAAAAAAAAAA

**Pull request closed without merging**
