### PR TITLE
Adds new Chaplain Ranks

### PR DESCRIPTION
**Pull request by Guidesu**
Hello, this is my first PR I hope I can learn more about coding and Pull requests.
I added these ranks:
E5
E6
W1
W2
To NTEF and SMC
I tested on my local server and worked!

🆑 
ADD:New ranks for chaplain

### CODE REVIEW

**Comment by Alanii** [comment]
Explain to me why, Chaplain has two enlisted ranks, and warrant ranks?

**Comment by Guidesu** [comment]
Welp, I wanted more roles to have a warrant officer...
Wich makes sense Chaplain be Warrant officer
And I chose two Warrants and enlisted because chaplain have two officers ranks

> Explain to me why, Chaplain has two enlisted ranks, and warrant ranks?

**Comment by Guidesu** [comment]
In discord this was my suggestion:
SUGGESTION:ADD more warrant officers in the game...
Please i beg you...
The only Roles i know you can be Warrant officer are:
Deck Officer
Shuttle Pilot
Senior Enginner
That it...
Maybe make Bio Tech Warrant Officer
Or Bridge Officers with a big maybe?
Scientist and roboticist too
Chaplain makes alot of sense thought...
Maybe Physician?
I am really limited to be Only a DO Warrant Officer

**Comment by Guidesu** [comment]
If you wish i can fix it.
But i am too new coding

**Comment by Guidesu** [comment]
I talked with Alanii so this is a big nooooo
At least i learned how to code and this make me happy
:)

**Pull request closed without merging**
