### PR TITLE
Revamped SSV 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by Kaksisilma**
Alright, so, this should properly work this time.
This PR changes the existing SSV (Skrellian Scout Vessel) almost entirely. Solars have been removed in favor of a Fusion core, Atmospherics should be more or less in pair with the Dagon; The SSV's Infirmary was beefed up; a slightly more spacious shuttle was also built, along with a new bridge, a brig, an office for the Vuxix, a bigger Gym, a better mess hall, a much more functional kitchen, a bigger hydroponics and a better restroom. along with a few more other things that shouldn't be as impactful.

This SHOULD be able to be properly merged right away given how broken the current SSV is, but I would still like to make sure everything is polished on the maps before this is merged. For now I'll just call it a day and look into it tomorrow aswell as write a proper changelog before I pass out, so, I'll open it as a draft for the time being. Might even throw in a few pictures once I get back wooo wooo.

### CODE REVIEW

**Comment by Mannybrado** [comment]
screenshots!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Kaksisilma** [comment]
Aight here are some screenshots. I'm going to start working on polishing it.


This is the bottom deck.

1-Area


And this is the upper deck.

2-Area

**Comment by Kaksisilma** [comment]
Capture



LETSFUCKINGGO

**Review by io-util — APPROVED** [review]
Diff in the .dme is pretty big but that can happen when shit messes up.

Skrell Reactor is just renamed ascent fusion, but that's fine.

**Comment by io-util** [comment]
Try to squash commits yourself next time, that's a lot of commits.

**Pull request merged**
