### PR TITLE
Access Fix

### PR DESCRIPTION
**Pull request by Mocha-Not-Latte**
they now have the basic access, wow. WHy the fuck they didn't have this already, is beyond me

EDIT: For CT, because I'm dumby and didn't write it before at midnight

### CODE REVIEW

**Comment by Lamasmaster** [comment]
Who has, you didnt specify whose access you modified.

**Comment by Alanii** [comment]
Hi.

I read your edit and edited this.

What basic access we talking about? Maintenance and shit or ????

**Comment by BurpleBineapple** [comment]
Looked into it, seems fine.

access_solgov_crew gives people access to things like the Byakhee's passenger area, faxes, crew lockers, that's all. Every other person on the ship has it so it's odd the CT doesn't.

**Review by BurpleBineapple — APPROVED** [review]
So yeah, approved

**Pull request merged**
