### PR TITLE
Added parry chance to crowbar, wrench and maglight

### PR DESCRIPTION
**Pull request by Jackofashepard**
Adds a parry chance to the crowbar and wrench

### CODE REVIEW

**Comment by gilvian** [comment]
why?

**Comment by Jackofashepard** [comment]
Purely because its a good makeshift melee weapon, you should be able to have a chance to block something with it

**Comment by ghost** [comment]
40% for a wrench
20% for a crowbar
30% for a fucking flashlight

Lmao, if this isn't a combat buff to whatever, I don't what is. I don't how a wrench believably on par with an actual melee weapon. A sword has the same amount as you're wanting to give the wrench, this seems like, I want to have an actual "makeshift" weapon by buffing it up to the standards of an actual weapon. Please explain how a sword and a wrench are both on par as weapons, I'm really thinking to how you achieved the thought process.

**Comment by Jackofashepard** [comment]
Based the parry mostly on size and damage, wrench doesnt do a lot of damage at all and is on the medium side of size so i gave it higher parry, maglight is essentially a sec trenchclub and the crowbar has really high damage and a slow swing so i made it parry a lot less.

Keep in mind this is just the base parry on the weapons, further parry is added or deducted based on the two combatants skills. If it could possibly block a attack it should have at least some parry, but definitely not on bays level where you can parry things with a pen

**Comment by BurpleBineapple** [comment]
I like the idea itself, but the values do seem a little odd. A crowbar? Alright. A heavy-duty flashlight? Maybe. A wrench being a better parry tool than a crowbar... not sure that makes sense logically.

I would recommend changing the wrench/flashlight to have the same parry value, since they're of the same size

**Comment by io-util** [comment]
Closing this as we are not reviewing / accepting PR's on our old repo anymore.
New Repo: https://github.com/VestaOfOrion/Vesta.Bay/

**Pull request closed without merging**
