### PR TITLE
The great language and cultural rework

### PR DESCRIPTION
**Pull request by Jackofashepard**
- Additional selectable languages limited to 1 from 3
- Background and Planet now play a huge role in what languages are granted and obtainable
- Removed terran options from xenos and extreme genemodders

Note: Genemodders were left with terran background as light genemodding is possible but frowned upon

### CODE REVIEW

**Comment by Ctr-Truescreen** [comment]
> Additional selectable languages limited to 1.

Uh oh, retcon alert. This one's really gonna fuck with my char.

**Comment by Jackofashepard** [comment]
You still get ZAC/spacer granted, then you get a language granted by background and then you can still select a additional language. That was limited or else you'd be able to string 4+ languages

**Comment by Jackofashepard** [comment]
All in all this is very similar to the original system except not everyone can get every language from everywhere making some languages exceedingly rare or tied to some faction

**Comment by Ctr-Truescreen** [comment]
> You still get ZAC/spacer granted, then you get a language granted by background and then you can still select a additional language. That was limited or else you'd be able to string 4+ languages

So does this mean i can still have Spacer & Sign Language by getting Spacer as a freebie alongside ZAC and then pick SL as an extra language?

**Comment by Jackofashepard** [comment]
You'd probably be able to get spacer freebie, ZAC freebie and something else as a extra. I dont think there's a way to surpass 3 languages on the dagon unless you are a certain species which gets granted their own languages

**Comment by Ctr-Truescreen** [comment]
> You'd probably be able to get spacer freebie, ZAC freebie and something else as a extra. I dont think there's a way to surpass 3 languages on the dagon unless you are a certain species which gets granted their own languages

Ok, if i can still get my ZAC, Spacer and SL combo, then this PR is fine.

**Comment by ghost** [comment]
Based change

How many people do you know that actually know more than one or two languages enough to fluently carry a conversation?

**Comment by Jackofashepard** [comment]
I should actually make this not have so many commits

**Comment by Jackofashepard** [comment]
Did some testing in game, few bugs i need to iron out before i can PR this

**Pull request closed without merging**
