### PR TITLE
Adds a new exoplanet ruin.

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
See the above.

This is what it looks like.

image

It looks better in-game, I swear.

### CODE REVIEW

**Comment by Jackofashepard** [comment]
Errors seem unrelated, we really need to find out what randomgen is causing these one day. Spoke too soon

**Comment by bearrrrrrrr** [comment]
What changes are needed?

**Comment by bearrrrrrrr** [comment]
i am  going to cry. fuck it we're doing it the right way i guess

**Comment by bearrrrrrrr** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Review by Jackofashepard — APPROVED** [review]

**Pull request merged**
