### PR TITLE
Thanos Snapping the EC, Part 1

### PR DESCRIPTION
**Pull request by BurpleBineapple**
Removed all remaining EC uniforms from starting job gear
Added new Fleet formal uniforms (dress and service) including a new set of officer/SNCO formals (Not usable without admin spawns yet.)

https://imgur.com/a/Q2wvazi <--- Imgur album of most of the uniforms

### CODE REVIEW

**Comment by ghost** [comment]
Pictures of new uniforms?

**Comment by Looreydev** [comment]
Very large diffs, you had the same issue Vhbraz had. Please fix that, also squash those 14 commits into 1.

**Review by io-util — CHANGES_REQUESTED** [review]
Please fix those big diffs first, you had the same issue @vhbraz also had. Additionally squash all of those commits into 1.

**Comment by io-util** [comment]
PR still has conflicts and is stale, reopen if you want to continue it.

**Pull request closed without merging**
