### PR TITLE
punitelli is dead

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
Punitelli died during an extended round. Extended rounds are canon. It was canon by 40-ish player vote that Punitelli is dead and has been replaced.

https://discordapp.com/channels/762930147371384834/768622213800263702/777119009350877214

RIP.

### CODE REVIEW

**Comment by Alanii** [comment]
What?

**Comment by Ctr-Truescreen** [comment]
> What?

My professional opinion?
The Punitelli was killed!

**Comment by bearrrrrrrr** [comment]
To clarify;
this PR changes Punitelli's name from 'Punitelli' to 'Punitelli II' and makes his mug a commemoration of our brave Warrant Officer.

**Review by io-util — APPROVED** [review]
Code is good, nothing big changed. Waiting on Lore confirmation.

**Comment by Stutternov** [comment]
This is Stutter the loremaint - this should be canon I can write up a document of the history of Punetelli and make sure it is no less that 250 words as per basic college standard essay. I'll even type it in Chicago style with footnotes.........

But seriously this is a funny-ass PR and I don't believe Jack would have a problem with it neither. I'll confirm it.

**Comment by Jackofashepard** [comment]
Waiting on alanii as all lore goes through them lastly before its approved

**Pull request merged**
