### PR TITLE
Medical Skill Cap Adjustment

### PR DESCRIPTION
**Pull request by N8-Toe**
Medtech looses Experienced Anatomy and gains Master Athletics

Trainee losses Experienced Anatomy and gains Master Athletics

Edited 11/26 to better reflect contents of PR

### CODE REVIEW

**Review by BurpleBineapple — COMMENTED** [review]
Your PR is doing something very different from what you've said.

You've given MTs trained anatomy and master athletics
You've taken away trainees having experienced anatomy for nothing in return

I don't **necessarily** have an issue with the changes? I'm very confused if this was a mistake or not.

Let me know either here or on discord what's up with it

**Comment by N8-Toe** [comment]
Changelog and description updated

I decided to go with giving Trainee's access to master athletics due to concern if MT's did and they didn't they would literally be unable to keep up.

**Review by BurpleBineapple — APPROVED** [review]
So to explain, athletics has nothing much to do with run speed. It only effects stamina. The difference between speed/stamina of experienced and master is negligible. There are other uses for athletics, most of which are for combat based roles.

That being said, after talking to some other dev staff, we don't want to give medical master athletics and hear the collective reeeeee from infantry/security who can't get master athletics I think removing experienced anatomy from MTs is good, they should not be able to do effective surgery but they don't necessarily need anything in return.

Removing experienced anatomy should be enough. No need for master athletics really.

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
Meant to hit "Request Changes" ;w;

**Review by BurpleBineapple — APPROVED** [review]
Going to go ahead with merging it as is. Time to get yelled at by security.

**Pull request merged**
