### PR TITLE
New SSV Roles based on sub-caste. New Exchange Qrii-Zuumqix slot for Humans. Also Ranks.

### PR DESCRIPTION
**Pull request by Kaksisilma**
This PR adds new job roles for the SSV based on subcaste:
1 slot for Qrii-Vuxix
2 slots for Xiqarr-Ketish & Alt titles
2 slots for Mero'to-Ketish & Alt titles
2 slots for Me'Kerr-Ketish & Alt Titles
1 slot for a human on an exchange program aboard the SSV.

:cl: Vhbraz
rscadd: SSV now has more and new slots based on specific job functions.
rscadd: SSV now has one slot for a human on an exchange program. (Keep in mind they'll need a SMC or NTEF background ICly)
rscadd: New ranks for skrell.
maptweak: Some nanopaste was added to facilitate repairing RIG modules.
rscadd: New adapted suit for a human aboard the SSV. Nearly a clone of the combat RIG minus a few sprite changes.
/:cl:
Here's character setup:

And here's both ranks. I am too lazy to upscale them, sorry.
Icon-Vuxix
Icon-Zuumqix

### CODE REVIEW

**Comment by Kaksisilma** [comment]
This is not complete but I will open it as a draft for travis while I work on a few issues.

**Comment by Kaksisilma** [comment]
There is a really annoying issue with the jobs.dm that does not allow off-ship IDs to update with alternative titles. It is beyond my capacity to handle. Given it's a relatively minor thing, I suppose it could be ignored if no one finds any way to fix it. For now I'll keep this as a draft.

**Comment by Kaksisilma** [comment]
Alright this should be working properly now, except for alt titles. However, you can choose your caste in-game to remedy that depending on your position. The Exchange Qrii-Zuumqix slot has also been added.

**Comment by Sun-Soaked** [comment]
I really, really like this, but I do have a slight concern- The SSV is generally played as a classified recon mission(Even if it does immediately reveal itself to the Dagon 9/10 rounds). Wouldn't the Skrell have issues with sending a human on a vessel full of classified military info and stealth technology?

**Comment by Kaksisilma** [comment]
> I really, really like this, but I do have a slight concern- The SSV is generally played as a classified recon mission(Even if it does immediately reveal itself to the Dagon 9/10 rounds). Wouldn't the Skrell have issues with sending a human on a vessel full of classified military info and stealth technology?

You raise a good point, but on the end this would be just like Skrell on the Dagon, but the opposite: Classified documents would likely be held by the Vuxix and out of reach of the Zuumqix. As for their technology, it is very unlikely that they would be able to reverse-engineer any of it. I like to think that the SDTF has extensive background checks for exchange personnel, just like the SFP (Sol federal police) probably has with xenos who decide to work on the Dagon.

I personally think it will bring quite an interesting experience and narrative on the table. It is common to see skrell on the Dagon, but seeing a human on the SSV is an extremely rare occurrence. This would also expand on the exchange program narrative. I'm anxious to see how the exchange thing goes but if it comes to it, those changes can easily be reversed.

Please feel free to bring any further concerns to me.

**Review by Jackofashepard — APPROVED** [review]

**Pull request merged**
