### PR TITLE
Medbay rework

### PR DESCRIPTION
**Pull request by Lamasmaster**
mediPR1
mediPR2
mediPR
mediPR3
mediPR4
mediPR5
mediPR6
mediPR7

### CODE REVIEW

**Comment by ghost** [comment]
What's wrong with current Medbay? There's zero detail in this PR about why this is necessary or a good change.

**Comment by Firefox13** [comment]
Disposals, wire to chemistry
Button to close EMT shutters
Lights in EMT, basically check every room for lights
Square carpet in break room
Did you even test it? I /very/ suggest doing that ㅡ you'll notice any missing lights and tiles, cameras too if you test an AI, areas, decals if you look closely.
Oh, and, decide if you want reinforced(preferred) or default walls around chemistry.

**Comment by Firefox13** [comment]
There is still stray pipes in chemistry and around the medbay as whole, chemistry is still walled off with mix of reinforced/non-reinforced walls, carpet in break room isn't square and there is still no lights in some of the rooms.
Perhaps there are still major problems with wires/atmospherics/disposals that go under windows/walls, even.
Can you, like, compile and launch the local server to see your changes?

**Review by io-util — CHANGES_REQUESTED** [review]
A disposals pipe that is just sitting alone in chemistry and there's no proper disposals anyway. Can't spot anything else from 6 seconds of looking at it, refer to the feedback of @Firefox13.

**Comment by io-util** [comment]
> A disposals pipe that is just sitting alone in chemistryand there's no proper disposals anyway. Can't spot anything else from 6 seconds of looking at it, refer to the feedback of @Firefox13.

Additionally I want this tested before it get's even close to being merged, already because you definitely did not test it, judging from how much is missing.

**Comment by io-util** [comment]
PR is stale, no communication at all since 6 days. If you want to address the changes re-open it or create a new one.

**Pull request closed without merging**
