### PR TITLE
Adds new AEG Sprites.

### PR DESCRIPTION
**Pull request by Kaksisilma**
This PR adds new Advanced Energy Gun sprites, made by yours truly.

It also adds some missing left-hand sprites, aswell as "polish" the sprite DMI files so that the right-hand and left-hand sprites are all mostly on the same place. (No more will the righthand AR be on the middle of the DMI page and the lefthand AR on the bottom)

show

:cl: Vhbraz
imagecadd: New animated AEG sprites for all the 3 firemodes.
:cl:

### CODE REVIEW

**Review by BurpleBineapple — APPROVED** [review]
Tested, all works, nice work

**Comment by BurpleBineapple** [comment]
Slapping DNM on this, Vhbraz wants to make improvements

**Comment by Kaksisilma** [comment]
Should be gucci to merge now. I will probably improve further upon it later but for now this is likely good enough.

**Comment by Kaksisilma** [comment]
Closing this because of the rebase. Also because I'll probably be improving it later.

**Pull request closed without merging**
