### PR TITLE
Makes the MSEA a SMC Attache

### PR DESCRIPTION
**Pull request by GrayRachnid**
What it says on the tin. Changes the MSEA to a Marine Attache role. The Marine Attache can be E7-E9(like the current MSEA) or O1-O3.

### CODE REVIEW

**Comment by N8-Toe** [comment]
I have not seen issues coming up from marine XO's, infact I think alot of the XO characters we have right now are marines. What issue is this aiming to fix?

**Comment by GrayRachnid** [comment]
> 
> 
> I have not seen issues coming up from marine XO's, infact I think alot of the XO characters we have right now are marines. What issue is this aiming to fix?

It makes no sense for the XO of an NTEF ship to be an SMC. The XO is in charge of /all/ personnel and any accommodations given to them it only makes sense that since the ship is owned and operated by the NTEF that the XO is NTEF as well. The new Attach role would give the SMC a place in the command structure and it also reminds them that the ship is mainly an NTEF one and not an SMC ship.

**Comment by Jackofashepard** [comment]
Maybe another day, but for today the coin hit tails

**Review by Jackofashepard — APPROVED** [review]

**Comment by Anton-Kr** [comment]
This PR killed Vesta

**Pull request merged**
