### PR TITLE
Brig Rework (again)

### PR DESCRIPTION
**Pull request by Lamasmaster**
PR12
PR13
PR14
PR15
PR17

### CODE REVIEW

**Comment by DiscordWizard** [comment]
I like the looks of the locker room, though I think the processing room is too small or has too little chairs for when things get a bit out of hands with multiple suspects, and the armory is divided into a room too much, the previous high alert / low alert room division worked well already. I do really like the mech charger addition tho
Also dunno what the last pic is on the brig, that single tile corridor looks too tight to be put into any important or integral part of the department, feels more like a maint tunnel

**Comment by ghost** [comment]
Single tile corridors bad
No idea why there's lockers in the prep room with the dinky smartpistols - assuming those are cadet lockers cadets don't get guns
Why are there three separate Armory rooms why are there three separate Armory rooms why are there three separate Armory rooms

The only part of the changes here I like are to the prep room, bar the smartpistols.

**Comment by Sun-Soaked** [comment]
I like the multi-fragmented armor any the prep room, but why is processing so tiny now? I've honestly had several experiences where our current processing is already too small.

**Comment by Firefox13** [comment]
изображение
please no

**Comment by Firefox13** [comment]
Please make sure that you don't get stuck between emergency airlocks if they trigger.
изображение
This corridor lacks fire/air alarms.
..And why this corridor seriously exists? You can try moving both cells to the right, so the corridor is near armory.

**Comment by Firefox13** [comment]
this is cadet sneak buff officially
изображение

**Comment by Lamasmaster** [comment]
The cadet locker "stealth" buff wasnt really stealth since I said before they should get atleast something and we agreed compacts will do.

**Pull request merged**
